# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "my-app-test"
client_id = "72dcfc9b356dcffabfd4d6a50499ab75"
application_url = "https://arms-scary-dawn-elections.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://arms-scary-dawn-elections.trycloudflare.com/auth/callback",
  "https://arms-scary-dawn-elections.trycloudflare.com/auth/shopify/callback",
  "https://arms-scary-dawn-elections.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "softpico-dev-store.myshopify.com"
